main: cx.ajneb97.Codex
version: 2.0.1
name: Codex
api-version: 1.13
author: Ajneb97
softdepend: [WorldGuard,WorldEdit,PlaceholderAPI,MythicMobs]

commands:
  codex:
    description: Main command of Codex